### ISSUE TITLE
Error: Tag/branch rwjblue/ember-qunit-builds#0.2.1 does not exist

### ISSUE THREAD

**Issue by kriswill** [rwjblue/ember-qunit-builds#2]
```sh
→ ember install:addon ember-cli-qunit
version: 0.1.12
Installed packages for tooling via npm.
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  not-cached git://github.com/rpflorence/ember-qunit.git#rwjblue/ember-qunit-builds#0.2.1
  cached git://github.com/stefanpenner/ember-cli-shims.git#0.0.3
  cached git://github.com/ember-cli/ember-cli-test-loader.git#0.1.0
  cached git://github.com/dockyard/ember-qunit-notifications.git#0.0.5
  cached git://github.com/jquery/qunit.git#1.17.1
Tag/branch rwjblue/ember-qunit-builds#0.2.1 does not exist
Error: Tag/branch rwjblue/ember-qunit-builds#0.2.1 does not exist
    at createError (/Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/lib/core/resolvers/GitResolver.js:182:15
    at /Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:1142:26
    at _fulfilled (/Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:749:13)
    at /Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:509:49
    at flush (/Users/kris/src/cg/web/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
```

**Comment by rwjblue** [comment]
Hmm, odd.  The tag definitely exists: https://github.com/rwjblue/ember-qunit-builds/tree/v0.2.1.

**Comment by backspace** [comment]
I was getting the same error trying to update to ember-qunit 0.2.0. I was able to [fix it](https://github.com/backspace/limitingdistance/commit/3fb821e30e2ce073623dddbcf4bbd29ae8d9ac51) by manually updating `bower.json` to use the [addon Bower blueprint line](https://github.com/ember-cli/ember-cli-qunit/blob/master/blueprints/ember-cli-qunit/index.js#L14):

        "ember-qunit": "rwjblue/ember-qunit-builds#0.2.1",

**Comment by rwjblue** [comment]
Should be all fixed now.
